### ISSUE TITLE
Forbidden/Not Found to js/img resources

### ISSUE THREAD

**Issue by EggIt** [mnapoli/bref-laravel-demo#4]
Hi,

I have deployed my laravel app to AWS by following this demo.
Deployment is successful and my app is running, the API Gateway forwards incoming requests to public/index.php and my view is rendering.

However, when my browser tries to download js and img resources:

1. i get a 403 Forbidden: which is due to the fact my laravel app is not aware of the deployment stage.
In fact, my browser issues a GET https://xxxx.amazonaws.com/js/app.js instead of https://xxxx.amazonaws.com/dev/js/app.js
I guess this is should be fixed by some configuration on the Gateway?

2. when i try to manually access https://xxxx.amazonaws.com/dev/js/app.js i get a 404 Not Found view from laravel app since i am going through the public/index.php handler.

My serverless.yml is identical to yours, i route all incoming requests to public/index.php.

How can i directy serve static resources and bypassing the handler?

**Comment by EggIt** [comment]
I post this response for someone who wanted to try Laravel on Lambda:
In addition to deploying laravel app as a lambda using serverless as described in this demo, i had to configure a CloudFront in front of my Gateway which responsibility is routing incoming requests to S3 or to Gateway.
For this, i have placed the public resources on an S3 Bucket (css, img, js folders) and configured the CloudFront using pathPatterns to serve these resources from S3 and all other requests from the API Gateway.

**Comment by mnapoli** [comment]
Hi @EggIt, sorry for not helping sooner. Yes CloudFront is a solution, I am working on a guide here: https://github.com/brefphp/bref/pull/268
